### ISSUE TITLE
Receiving error when running script

### ISSUE THREAD

**Issue by brunchey** [SumoLogic/sumologic-mongodb-atlas#3] opened 2019-09-18 12:38 UTC
Hello I am running this script in a docker container and am receiving the following error...

sumoappclient.sumoclient.base | API Type: 5d68212b553855638ce08134-proda-shard-00-02-hbeft.mongodb.net-mongodb.gz thread generated an exception: ('Unknown string format:', '"$or":')

The docker image I am using is python:3.7.4-slim-buster.

**Comment by himanshu219** [comment] 2020-10-02 05:48
This is because of multi line message it was rare to reproduce this would be fixed in #7

**Comment by himanshu219** [comment] 2020-10-02 05:49
We have already released new version 1.0.15 of SAM application and 1.0.8 of onprem python package. You can try them out

**Closed** 2020-10-23 10:51 UTC
